"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  buildPropertyFromIntake,
  saveIntakeStubToSession,
  slugify,
  type IntakeFormInput,
} from "@/lib/intake-property-stub";

function escapeTsString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildStub(form: IntakeFormInput): string {
  const property = buildPropertyFromIntake(form);
  const id = property.id;
  const isSample = Boolean(property.isSample);
  const whatIsKnown = form.notes.trim()
    ? `[\n      "${escapeTsString(form.notes.trim())}",\n    ]`
    : "[]";

  const exportName = `property${id
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")}`;

  if (!isSample) {
    return `import type { PropertyScreen } from "@/types/property";

// Generated by /intake — minimal identity stub.
// Next: save as src/data/properties/${id}.ts, register in index.ts.
// For the full blank shape (association/taxes/identifiers), copy _template.ts and merge these fields.

export const ${exportName}: PropertyScreen = {
  id: "${id}",
  title: "${escapeTsString(property.title)}",
  address: "${escapeTsString(property.address)}",
  city: "${escapeTsString(property.city)}",
  state: "${escapeTsString(property.state)}",
  zip: "${escapeTsString(property.zip)}",
  county: ${property.county ? `"${escapeTsString(property.county)}"` : "undefined"},
  propertyType: "Condominium",
  stage: "screening",
  status: {
    currentRecommendation: "Need More Information",
    provisionalStatus: "need-more-information",
  },
  summary: {
    whatIsKnown: ${whatIsKnown},
    publicRiskSignals: [],
    strengths: [],
    risks: [],
  },
  taxes: {
    annualHistory: [],
  },
  missingDiligence: [],
  condoRiskFlags: {
    milestoneInspection: { status: "unknown", label: "Milestone inspection", note: "Not yet reviewed." },
    sirsReserves: { status: "unknown", label: "SIRS / reserves", note: "Not yet reviewed." },
    specialAssessments: { status: "unknown", label: "Special assessments", note: "Not yet reviewed." },
    hoaDues: { status: "unknown", label: "HOA dues", note: "Not yet verified. Keep proForma.hoaMonthly null until confirmed." },
    insurance: { status: "unknown", label: "Insurance", note: "Not yet researched." },
    litigationOrRecords: { status: "unknown", label: "Litigation / records", note: "Not yet reviewed." },
  },
  screening: {
    targetCashOnCash: null,
    hardNoRedFlag: "unknown",
    rentSupportable: "unknown",
    associationRiskNormal: "unknown",
  },
  proForma: {
    expectedMarketRentMonthly: null,
    hoaMonthly: null,
    insuranceAnnual: null,
    repairsAnnual: null,
    vacancyRate: null,
  },
  sources: [],
  referencePaths: [],
};
`;
  }

  return `import type { PropertyScreen } from "@/types/property";

// Generated by /intake — SAMPLE identity stub (workflow practice only).
// Next: save as src/data/properties/${id}.ts, register in index.ts.
// After registration, list/detail will show the Sample badge.
// For the full blank shape (association/taxes/identifiers), copy _template.ts and merge these fields.

export const ${exportName}: PropertyScreen = {
  id: "${id}",
  title: "${escapeTsString(property.title)}",
  address: "${escapeTsString(property.address)}",
  city: "${escapeTsString(property.city)}",
  state: "${escapeTsString(property.state)}",
  zip: "${escapeTsString(property.zip)}",
  county: ${property.county ? `"${escapeTsString(property.county)}"` : "undefined"},
  isSample: true,
  sampleNote: "${escapeTsString(property.sampleNote ?? "")}",
  propertyType: undefined,
  status: {
    currentRecommendation: "Need More Information",
    provisionalStatus: "need-more-information",
  },
  summary: {
    purpose: "Sample identity shell for workflow practice. Underwriting inputs are intentionally unset.",
    whatIsKnown: ${whatIsKnown},
    publicRiskSignals: [],
    strengths: [],
    risks: [],
  },
  taxes: {
    annualHistory: [],
  },
  missingDiligence: [],
  condoRiskFlags: {
    milestoneInspection: { status: "unknown", label: "Milestone inspection", note: "Not yet reviewed." },
    sirsReserves: { status: "unknown", label: "SIRS / reserves", note: "Not yet reviewed." },
    specialAssessments: { status: "unknown", label: "Special assessments", note: "Not yet reviewed." },
    hoaDues: { status: "unknown", label: "HOA dues", note: "Not yet verified. Keep proForma.hoaMonthly null until confirmed." },
    insurance: { status: "unknown", label: "Insurance", note: "Not yet researched." },
    litigationOrRecords: { status: "unknown", label: "Litigation / records", note: "Not yet reviewed." },
  },
  screening: {
    targetCashOnCash: null,
    hardNoRedFlag: "unknown",
    rentSupportable: "unknown",
    associationRiskNormal: "unknown",
  },
  proForma: {
    expectedMarketRentMonthly: null,
    hoaMonthly: null,
    insuranceAnnual: null,
    repairsAnnual: null,
    vacancyRate: null,
  },
  sources: [],
  referencePaths: [],
};
`;
}

export default function IntakePage() {
  const router = useRouter();
  const [form, setForm] = useState<IntakeFormInput>({
    title: "",
    address: "",
    city: "",
    state: "FL",
    zip: "",
    county: "",
    notes: "",
    isSample: false,
  });
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);

  const stub = useMemo(() => buildStub(form), [form]);
  const suggestedPath = `src/data/properties/${slugify(`${form.address}-${form.zip}`)}.ts`;

  function updateField<K extends keyof IntakeFormInput>(
    key: K,
    value: IntakeFormInput[K]
  ) {
    setForm((current) => ({ ...current, [key]: value }));
    setCopied(false);
    setCopyError(false);
  }

  async function copyStub() {
    try {
      await navigator.clipboard.writeText(stub);
      setCopied(true);
      setCopyError(false);
    } catch {
      setCopied(false);
      setCopyError(true);
    }
  }

  function openDemoStub() {
    const property = buildPropertyFromIntake(form, { forceSample: true });
    saveIntakeStubToSession(property);
    router.push("/properties/intake-stub");
  }

  return (
    <main className="page-stack">
      <section className="page-intro">
        <h1>Property stub generator</h1>
        <p>
          Developer / operator tool: generate TypeScript for the repo. This does
          not save a deal in the app — copy the stub into{" "}
          <code>src/data/properties</code> and register it in{" "}
          <code>index.ts</code>. Optional: open a one-tab Sample shell for
          layout practice. For association / tax / identifier sections, copy{" "}
          <code>_template.ts</code> and merge identity fields from this stub.
        </p>
      </section>

      <section className="section-card">
        <h2>Address details</h2>
        <div className="section-card__body">
          <form
            className="intake-form"
            onSubmit={(event) => {
              event.preventDefault();
              void copyStub();
            }}
          >
            <label>
              Title (optional)
              <input
                value={form.title}
                onChange={(event) => updateField("title", event.target.value)}
                placeholder="Florida Deal Screen — 123 Main St #1"
              />
            </label>
            <label>
              Address
              <input
                required
                value={form.address}
                onChange={(event) => updateField("address", event.target.value)}
                placeholder="7863 Niagara Ave #1921"
              />
            </label>
            <div className="intake-form__row">
              <label>
                City
                <input
                  required
                  value={form.city}
                  onChange={(event) => updateField("city", event.target.value)}
                  placeholder="Tampa"
                />
              </label>
              <label>
                State
                <input
                  required
                  value={form.state}
                  onChange={(event) => updateField("state", event.target.value)}
                  placeholder="FL"
                />
              </label>
              <label>
                ZIP
                <input
                  required
                  value={form.zip}
                  onChange={(event) => updateField("zip", event.target.value)}
                  placeholder="33617"
                />
              </label>
            </div>
            <label>
              County (optional)
              <input
                value={form.county}
                onChange={(event) => updateField("county", event.target.value)}
                placeholder="Hillsborough County"
              />
            </label>
            <label>
              Notes (optional)
              <textarea
                rows={3}
                value={form.notes}
                onChange={(event) => updateField("notes", event.target.value)}
                placeholder="Why this deal was selected / first diligence notes"
              />
            </label>
            <label
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                fontWeight: 600,
                color: "#4b5563",
                fontSize: 13,
              }}
            >
              <input
                type="checkbox"
                checked={form.isSample}
                onChange={(event) =>
                  updateField("isSample", event.target.checked)
                }
              />
              <span>Mark as sample / workflow practice</span>
            </label>
            <p className="muted-note">
              Sample mode creates a clearly labeled identity shell for testing
              only — not a live underwriting record.{" "}
              <strong>Open demo stub</strong> always opens as Sample in this tab
              only.
            </p>
            <div className="intake-form__actions">
              <button type="submit" className="button-primary">
                {copied ? "Copied" : "Copy TypeScript stub"}
              </button>
              <button
                type="button"
                className="doc-state-actions__btn"
                onClick={openDemoStub}
              >
                Open demo stub
              </button>
              <span className="muted-note">
                Suggested file: <code>{suggestedPath}</code>
              </span>
            </div>
            <p className="muted-note">
              Open demo stub opens a Sample practice shell in this browser tab
              only — not saved to the repo. Use Copy stub to register a real
              file.
            </p>
            {copyError ? (
              <p className="muted-note">
                Copy failed — select the stub below and copy manually.
              </p>
            ) : null}
            <p className="muted-note">
              Minimal stub for a quick start. Copy{" "}
              <code>_template.ts</code> if you want the full blank shape.
            </p>
          </form>
        </div>
      </section>

      <section className="section-card">
        <h2>Generated stub</h2>
        <p className="section-card__subtitle">
          Paste into the suggested file, then add the export to{" "}
          <code>src/data/properties/index.ts</code>. Or start from{" "}
          <code>_template.ts</code> if you prefer a fuller blank shape.
        </p>
        <div className="section-card__body">
          <pre className="intake-stub">{stub}</pre>
        </div>
      </section>
    </main>
  );
}
